In [4]:
import pandas as pd
import numpy as np 
import hashlib

## Dados


### `Analise das fontes de dados:`
_____________________________________
_____________________________________


### Scrape ufc stats

In [51]:
event_details = pd.read_csv(r'C:\Users\edude\OneDrive\Área de Trabalho\Códigos\Faculdade\TCC\LabA\base_dados\processed_bronze\1.scrape_ufc_stats\event_details.csv')
fight_details = pd.read_csv(r'C:\Users\edude\OneDrive\Área de Trabalho\Códigos\Faculdade\TCC\LabA\base_dados\processed_bronze\1.scrape_ufc_stats\fight_details.csv')
fight_results = pd.read_csv(r'C:\Users\edude\OneDrive\Área de Trabalho\Códigos\Faculdade\TCC\LabA\base_dados\processed_bronze\1.scrape_ufc_stats\fight_results.csv')
fight_stats = pd.read_csv(r'C:\Users\edude\OneDrive\Área de Trabalho\Códigos\Faculdade\TCC\LabA\base_dados\processed_bronze\1.scrape_ufc_stats\fight_stats.csv')
fighter_details = pd.read_csv(r'C:\Users\edude\OneDrive\Área de Trabalho\Códigos\Faculdade\TCC\LabA\base_dados\processed_bronze\1.scrape_ufc_stats\fighter_details.csv')
fighter_tott = pd.read_csv(r'C:\Users\edude\OneDrive\Área de Trabalho\Códigos\Faculdade\TCC\LabA\base_dados\processed_bronze\1.scrape_ufc_stats\fighter_tott.csv')

In [52]:
display(event_details)
display(fight_details[fight_details['event_name']=='UFC Fight Night: Allen vs. Costa'])
display(fight_results[fight_results['event_name']=='UFC Fight Night: Allen vs. Costa'])
display(fight_stats[fight_stats['event_name']=='UFC Fight Night: Allen vs. Costa'])
# display(fighter_details)
display(fighter_tott[fighter_tott['fighter_name'].isin(['Arnold Allen','Melquizael Costa'])])

,event_name,url,event_date,event_location
0,UFC Fight Night: Allen vs. Costa,http://ufcstats.com/event-details/73abb7a5c57f...,2026-05-16,"Las Vegas, Nevada, USA"
1,UFC 328: Chimaev vs. Strickland,http://ufcstats.com/event-details/9eedac48b497...,2026-05-09,"Newark, New Jersey, USA"
2,UFC Fight Night: Della Maddalena vs. Prates,http://ufcstats.com/event-details/872b018076f8...,2026-05-02,"Perth, Western Australia, Australia"
3,UFC Fight Night: Sterling vs. Zalal,http://ufcstats.com/event-details/e60d773a0a42...,2026-04-25,"Las Vegas, Nevada, USA"
4,UFC Fight Night: Burns vs. Malott,http://ufcstats.com/event-details/c3ac8d0da7b0...,2026-04-18,"Winnipeg, Manitoba, Canada"
...,...,...,...,...
769,UFC 6: Clash of the Titans,http://ufcstats.com/event-details/1c3f5e85b59e...,1995-07-14,"Casper, Wyoming, USA"
770,UFC 5: The Return of the Beast,http://ufcstats.com/event-details/dedc3bb440d0...,1995-04-07,"Charlotte, North Carolina, USA"
771,UFC 4: Revenge of the Warriors,http://ufcstats.com/event-details/b60391da771d...,1994-12-16,"Tulsa, Oklahoma, USA"
772,UFC 3: The American Dream,http://ufcstats.com/event-details/1a49e0670dfa...,1994-09-09,"Charlotte, North Carolina, USA"
773,UFC 2: No Way Out,http://ufcstats.com/event-details/a6a9ab5a824e...,1994-03-11,"Denver, Colorado, USA"

,event_name,bout,url
0,UFC Fight Night: Allen vs. Costa,Arnold Allen vs. Melquizael Costa,http://ufcstats.com/fight-details/e4aa60812489...
1,UFC Fight Night: Allen vs. Costa,Dooho Choi vs. Daniel Santos,http://ufcstats.com/fight-details/fc1266e2892e...
2,UFC Fight Night: Allen vs. Costa,Malcolm Wellmaker vs. Juan Diaz,http://ufcstats.com/fight-details/ecb7ff543dd4...
3,UFC Fight Night: Allen vs. Costa,Modestas Bukauskas vs. Christian Edwards,http://ufcstats.com/fight-details/57bd683efc79...
4,UFC Fight Night: Allen vs. Costa,Timmy Cuamba vs. Benardo Sopaj,http://ufcstats.com/fight-details/a6ec8573a9d3...
5,UFC Fight Night: Allen vs. Costa,Nikolay Veretennikov vs. Khaos Williams,http://ufcstats.com/fight-details/ec32745308e2...
6,UFC Fight Night: Allen vs. Costa,Tuco Tokkos vs. Ivan Erslan,http://ufcstats.com/fight-details/6242cda790f2...
7,UFC Fight Night: Allen vs. Costa,Tommy Gantt vs. Artur Minev,http://ufcstats.com/fight-details/c9e0aa88afb8...
8,UFC Fight Night: Allen vs. Costa,Ketlen Vieira vs. Jacqueline Cavalcanti,http://ufcstats.com/fight-details/5f7111b982bc...
9,UFC Fight Night: Allen vs. Costa,Cody Brundage vs. Andre Petroski,http://ufcstats.com/fight-details/48cb604345f1...
10,UFC Fight Night: Allen vs. Costa,Alice Ardelean vs. Polyana Viana,http://ufcstats.com/fight-details/b98ead4eff6b...
11,UFC Fight Night: Allen vs. Costa,Daniel Barez vs. Luis Gurule,http://ufcstats.com/fight-details/b482d4452e4d...
12,UFC Fight Night: Allen vs. Costa,Shauna Bannon vs. Nicolle Caliari,http://ufcstats.com/fight-details/39417b7d07c2...

,event_name,bout,outcome,weight_class,method,round,time,time_format,referee,details,url,round_number
0,UFC Fight Night: Allen vs. Costa,Arnold Allen vs. Melquizael Costa,W/L,Featherweight Bout,Decision - Unanimous,5,5:00,5 Rnd (5-5-5-5-5),Chris Tognoni,Eric Colon 45 - 50.David Lethaby 45 - 50.Sal D...,http://ufcstats.com/fight-details/e4aa60812489...,5
1,UFC Fight Night: Allen vs. Costa,Dooho Choi vs. Daniel Santos,W/L,Featherweight Bout,KO/TKO,2,4:29,3 Rnd (5-5-5),Kerry Hatley,Punch to Body At Distance,http://ufcstats.com/fight-details/fc1266e2892e...,2
2,UFC Fight Night: Allen vs. Costa,Malcolm Wellmaker vs. Juan Diaz,L/W,Bantamweight Bout,Submission,2,4:08,3 Rnd (5-5-5),Eric McMahon,Rear Naked Choke,http://ufcstats.com/fight-details/ecb7ff543dd4...,2
3,UFC Fight Night: Allen vs. Costa,Modestas Bukauskas vs. Christian Edwards,W/L,Catch Weight Bout,Decision - Split,3,5:00,3 Rnd (5-5-5),Kerry Hatley,David Sutherland 28 - 29.Junichiro Kamijo 29 -...,http://ufcstats.com/fight-details/57bd683efc79...,3
4,UFC Fight Night: Allen vs. Costa,Timmy Cuamba vs. Benardo Sopaj,L/W,Bantamweight Bout,Submission,2,2:25,3 Rnd (5-5-5),Jerin Valel,Rear Naked Choke,http://ufcstats.com/fight-details/a6ec8573a9d3...,2
5,UFC Fight Night: Allen vs. Costa,Nikolay Veretennikov vs. Khaos Williams,L/W,Welterweight Bout,KO/TKO,1,3:31,3 Rnd (5-5-5),Chris Tognoni,Punches to Head At Distance,http://ufcstats.com/fight-details/ec32745308e2...,1
6,UFC Fight Night: Allen vs. Costa,Tuco Tokkos vs. Ivan Erslan,L/W,Light Heavyweight Bout,Decision - Unanimous,3,5:00,3 Rnd (5-5-5),Eric McMahon,Adalaide Byrd 28 - 29.Junichiro Kamijo 28 - 29...,http://ufcstats.com/fight-details/6242cda790f2...,3
7,UFC Fight Night: Allen vs. Costa,Tommy Gantt vs. Artur Minev,W/L,Lightweight Bout,KO/TKO,2,2:51,3 Rnd (5-5-5),Kerry Hatley,Punches to Head From Back Control,http://ufcstats.com/fight-details/c9e0aa88afb8...,2
8,UFC Fight Night: Allen vs. Costa,Ketlen Vieira vs. Jacqueline Cavalcanti,W/L,Women's Bantamweight Bout,Decision - Unanimous,3,5:00,3 Rnd (5-5-5),Jerin Valel,Eric Colon 28 - 29.Sal D'amato 28 - 29.David L...,http://ufcstats.com/fight-details/5f7111b982bc...,3
9,UFC Fight Night: Allen vs. Costa,Cody Brundage vs. Andre Petroski,W/L,Middleweight Bout,KO/TKO,2,0:44,3 Rnd (5-5-5),Chris Tognoni,Punches to Head From Guard,http://ufcstats.com/fight-details/48cb604345f1...,2
10,UFC Fight Night: Allen vs. Costa,Alice Ardelean vs. Polyana Viana,W/L,Women's Strawweight Bout,Submission,2,4:36,3 Rnd (5-5-5),Eric McMahon,Calf Slicer From GuardCapsule lock,http://ufcstats.com/fight-details/b98ead4eff6b...,2
11,UFC Fight Night: Allen vs. Costa,Daniel Barez vs. Luis Gurule,L/W,Flyweight Bout,Decision - Unanimous,3,5:00,3 Rnd (5-5-5),Jerin Valel,Eric Colon 27 - 30.Junichiro Kamijo 27 - 30.To...,http://ufcstats.com/fight-details/b482d4452e4d...,3
12,UFC Fight Night: Allen vs. Costa,Shauna Bannon vs. Nicolle Caliari,L/W,Women's Strawweight Bout,Submission,3,3:08,3 Rnd (5-5-5),Kerry Hatley,Arm Triangle From Side Control,http://ufcstats.com/fight-details/39417b7d07c2...,3

,event_name,bout,round,fighter_name,knockdowns,sig_str,sig_str_pct,total_str,takedowns,takedown_pct,...,body_str_landed,body_str_attempted,leg_str_landed,leg_str_attempted,distance_str_landed,distance_str_attempted,clinch_str_landed,clinch_str_attempted,ground_str_landed,ground_str_attempted
0,UFC Fight Night: Allen vs. Costa,Arnold Allen vs. Melquizael Costa,Round 1,Arnold Allen,1.0,9 of 9,100%,18 of 20,2 of 2,100%,...,0.0,0.0,1.0,1.0,4.0,4.0,0.0,0.0,5.0,5.0
1,UFC Fight Night: Allen vs. Costa,Arnold Allen vs. Melquizael Costa,Round 2,Arnold Allen,0.0,23 of 38,60%,28 of 44,0 of 0,NaN,...,2.0,2.0,5.0,5.0,23.0,38.0,0.0,0.0,0.0,0.0
2,UFC Fight Night: Allen vs. Costa,Arnold Allen vs. Melquizael Costa,Round 3,Arnold Allen,0.0,32 of 52,61%,44 of 66,0 of 0,NaN,...,2.0,2.0,3.0,3.0,25.0,45.0,0.0,0.0,7.0,7.0
3,UFC Fight Night: Allen vs. Costa,Arnold Allen vs. Melquizael Costa,Round 4,Arnold Allen,0.0,23 of 36,63%,26 of 41,1 of 1,100%,...,1.0,1.0,2.0,2.0,23.0,35.0,0.0,1.0,0.0,0.0
4,UFC Fight Night: Allen vs. Costa,Arnold Allen vs. Melquizael Costa,Round 5,Arnold Allen,0.0,11 of 17,64%,40 of 51,4 of 4,100%,...,1.0,2.0,0.0,0.0,4.0,9.0,0.0,1.0,7.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,UFC Fight Night: Allen vs. Costa,Shauna Bannon vs. Nicolle Caliari,Round 2,Shauna Bannon,0.0,20 of 28,71%,64 of 76,0 of 0,NaN,...,7.0,8.0,0.0,2.0,10.0,17.0,1.0,2.0,9.0,9.0
62,UFC Fight Night: Allen vs. Costa,Shauna Bannon vs. Nicolle Caliari,Round 3,Shauna Bannon,0.0,7 of 14,50%,12 of 19,0 of 1,0%,...,2.0,3.0,3.0,3.0,7.0,14.0,0.0,0.0,0.0,0.0
63,UFC Fight Night: Allen vs. Costa,Shauna Bannon vs. Nicolle Caliari,Round 1,Nicolle Caliari,0.0,6 of 9,66%,25 of 28,2 of 2,100%,...,1.0,1.0,0.0,0.0,4.0,7.0,0.0,0.0,2.0,2.0
64,UFC Fight Night: Allen vs. Costa,Shauna Bannon vs. Nicolle Caliari,Round 2,Nicolle Caliari,0.0,6 of 14,42%,10 of 18,1 of 6,16%,...,1.0,1.0,0.0,0.0,1.0,9.0,1.0,1.0,4.0,4.0
65,UFC Fight Night: Allen vs. Costa,Shauna Bannon vs. Nicolle Caliari,Round 3,Nicolle Caliari,0.0,8 of 15,53%,15 of 22,1 of 1,100%,...,0.0,1.0,0.0,0.0,3.0,10.0,1.0,1.0,4.0,4.0

,fighter_name,height,weight,reach,stance,date_of_birth,url,height_cm,weight_lbs,reach_inches,reach_cm
85,Arnold Allen,"5' 8""",145 lbs.,"70""",Southpaw,1994-01-22,http://ufcstats.com/fighter-details/040a74bb0a...,172.72,145.0,70.0,177.80
782,Melquizael Costa,"5' 10""",145 lbs.,"71""",Southpaw,1996-09-14,http://ufcstats.com/fighter-details/20bccc9bb4...,177.80,145.0,71.0,180.34

### Fonte de dados
- Local: C:\Users\edude\OneDrive\Área de Trabalho\Códigos\Faculdade\TCC\LabA\base_dados\processed_bronze\scrape_ufc_stats.  
- Origem: scraping disponível em https://github.com/Greco1899/scrape_ufc_stats (ufcstats).  
- Período coberto: eventos de 1994-03 até 2026-05.

______________
### UFC datasets

In [33]:
ufc_dataset = pd.read_csv(r'C:\Users\edude\OneDrive\Área de Trabalho\Códigos\Faculdade\TCC\LabA\base_dados\processed_bronze\ufc_datasets\ufc.csv')

In [34]:
display(
    ufc_dataset[
        ufc_dataset["fight_id"] =='3ce96bb0c69b39be'
    ]
)

,event_id,event_name,date,location,fight_id,division,title_fight,method,finish_round,match_time_sec,...,blue_td_avg,blue_td_avg_acc,blue_td_def,blue_sub_avg,winner,winner_id,red_weight_lbs,red_reach_inches,blue_weight_lbs,blue_reach_inches
730,899eaba48fa864a6,UFC Fight Night: Allen vs. Curtis 2,2024-04-06,"Las Vegas, Nevada, USA",3ce96bb0c69b39be,middleweight,0,Decision - Split,5,300,...,0.0,0,82,0.0,Brendan Allen,2f181c0467965b98,83.91,190.5,77.11,190.5

In [35]:
print(
    ufc_dataset[
        ufc_dataset["fight_id"] == "3ce96bb0c69b39be"
    ].to_json(orient="records", indent=2, force_ascii=False)
)

[
  {
    "event_id":"899eaba48fa864a6",
    "event_name":"UFC Fight Night: Allen vs. Curtis 2",
    "date":"2024-04-06",
    "location":"Las Vegas, Nevada, USA",
    "fight_id":"3ce96bb0c69b39be",
    "division":"middleweight",
    "title_fight":0,
    "method":"Decision - Split",
    "finish_round":5,
    "match_time_sec":300,
    "total_rounds":5.0,
    "referee":"Mark Smith",
    "red_name":"Brendan Allen",
    "red_id":"2f181c0467965b98",
    "red_kd":0.0,
    "red_sig_str_landed":112.0,
    "red_sig_str_atmpted":222.0,
    "red_sig_str_acc":50.0,
    "red_total_str_landed":128.0,
    "red_total_str_atmpted":242.0,
    "red_total_str_acc":53.0,
    "red_td_landed":6.0,
    "red_td_atmpted":13.0,
    "red_td_acc":46.0,
    "red_sub_att":0.0,
    "red_ctrl":365.0,
    "red_head_landed":72.0,
    "red_head_atmpted":172.0,
    "red_head_acc":42.0,
    "red_body_landed":25.0,
    "red_body_atmpted":34.0,
    "red_body_acc":74.0,
    "red_leg_landed":15.0,
    "red_leg_atmpted":16.0,
    "red_leg_acc":94.0,
    "red_dist_landed":108.0,
    "red_dist_atmpted":214.0,
    "red_dist_acc":50.0,
    "red_clinch_landed":4.0,
    "red_clinch_atmpted":8.0,
    "red_clinch_acc":50.0,
    "red_ground_landed":0.0,
    "red_ground_atmpted":0.0,
    "red_ground_acc":null,
    "red_landed_head_per":64.0,
    "red_landed_body_per":22.0,
    "red_landed_leg_per":13.0,
    "red_landed_dist_per":96.0,
    "red_landed_clinch_per":3.0,
    "red_landed_ground_per":0.0,
    "red_nick_name":"All In",
    "red_wins":25,
    "red_losses":7,
    "red_draws":0,
    "red_height":187.96,
    "red_weight":83.91,
    "red_reach":190.5,
    "red_stance":"Orthodox",
    "red_dob":"1995\/12\/28",
    "red_splm":3.85,
    "red_str_acc":53,
    "red_sapm":3.96,
    "red_str_def":47,
    "red_td_avg":1.65,
    "red_td_avg_acc":41,
    "red_td_def":56,
    "red_sub_avg":1.2,
    "blue_name":"Chris Curtis",
    "blue_id":"5442f1bc4b47eaf3",
    "blue_kd":0.0,
    "blue_sig_str_landed":124.0,
    "blue_sig_str_atmpted":241.0,
    "blue_sig_str_acc":51.0,
    "blue_total_str_landed":141.0,
    "blue_total_str_atmpted":261.0,
    "blue_total_str_acc":54.0,
    "blue_td_landed":0.0,
    "blue_td_atmpted":0.0,
    "blue_td_acc":null,
    "blue_sub_att":0.0,
    "blue_ctrl":78.0,
    "blue_head_landed":96.0,
    "blue_head_atmpted":205.0,
    "blue_head_acc":47.0,
    "blue_body_landed":25.0,
    "blue_body_atmpted":33.0,
    "blue_body_acc":76.0,
    "blue_leg_landed":3.0,
    "blue_leg_atmpted":3.0,
    "blue_leg_acc":100.0,
    "blue_dist_landed":122.0,
    "blue_dist_atmpted":237.0,
    "blue_dist_acc":51.0,
    "blue_clinch_landed":2.0,
    "blue_clinch_atmpted":4.0,
    "blue_clinch_acc":50.0,
    "blue_ground_landed":0.0,
    "blue_ground_atmpted":0.0,
    "blue_ground_acc":null,
    "blue_landed_head_per":77.0,
    "blue_landed_body_per":20.0,
    "blue_landed_leg_per":2.0,
    "blue_landed_dist_per":98.0,
    "blue_landed_clinch_per":1.0,
    "blue_landed_ground_per":0.0,
    "blue_nick_name":"Action-Man",
    "blue_wins":32,
    "blue_losses":12,
    "blue_draws":0,
    "blue_height":177.8,
    "blue_weight":77.11,
    "blue_reach":190.5,
    "blue_stance":"Orthodox",
    "blue_dob":"1987\/07\/15",
    "blue_splm":5.98,
    "blue_str_acc":50,
    "blue_sapm":6.19,
    "blue_str_def":54,
    "blue_td_avg":0.0,
    "blue_td_avg_acc":0,
    "blue_td_def":82,
    "blue_sub_avg":0.0,
    "winner":"Brendan Allen",
    "winner_id":"2f181c0467965b98",
    "red_weight_lbs":83.91,
    "red_reach_inches":190.5,
    "blue_weight_lbs":77.11,
    "blue_reach_inches":190.5
  }
]

### Fonte de dados
- Local: C:\Users\edude\OneDrive\Área de Trabalho\Códigos\Faculdade\TCC\LabA\base_dados\processed_bronze\ufc_datasets  
- Origem: Keagle - kaggle.com/datasets/neelagiriaditya/ufc-datasets-1994-2025
- Período coberto: eventos de 1994-03 até 2025-09.


#### Resumo
Temos uma basee que centraliza todas as informações nomeda como ufc.csv

______________
### UFC datalabs

In [ ]:
merged_stats_n_scorecards = pd.read_csv(r'C:\Users\edude\OneDrive\Área de Trabalho\Códigos\Faculdade\TCC\LabA\base_dados\processed_bronze\3.ufc_datalab\merged_stats_n_scorecards.csv')
raw_fighter_details = pd.read_csv(r'C:\Users\edude\OneDrive\Área de Trabalho\Códigos\Faculdade\TCC\LabA\base_dados\processed_bronze\3.ufc_datalab\raw_fighter_details.csv')
scorecards = pd.read_csv(r'C:\Users\edude\OneDrive\Área de Trabalho\Códigos\Faculdade\TCC\LabA\base_dados\processed_bronze\3.ufc_datalab\scorecards.csv')
stats_processed_all_bouts = pd.read_csv(r'C:\Users\edude\OneDrive\Área de Trabalho\Códigos\Faculdade\TCC\LabA\base_dados\processed_bronze\3.ufc_datalab\stats_processed_all_bouts.csv')
stats_processed = pd.read_csv(r'C:\Users\edude\OneDrive\Área de Trabalho\Códigos\Faculdade\TCC\LabA\base_dados\processed_bronze\3.ufc_datalab\stats_processed.csv')
stats_raw = pd.read_csv(r'C:\Users\edude\OneDrive\Área de Trabalho\Códigos\Faculdade\TCC\LabA\base_dados\processed_bronze\3.ufc_datalab\stats_raw.csv')

C:\Users\edude\AppData\Local\Temp\ipykernel_8512\63130270.py:1: DtypeWarning: Columns (60,61) have mixed types. Specify dtype option on import or set low_memory=False.
  merged_stats_n_scorecards = pd.read_csv(r'C:\Users\edude\OneDrive\Área de Trabalho\Códigos\Faculdade\TCC\LabA\base_dados\processed_bronze\3.ufc_datalab\merged_stats_n_scorecards.csv')

In [40]:
display(merged_stats_n_scorecards[merged_stats_n_scorecards["event_name"] == "UFC Fight Night: Fiziev vs. Torres"])
display(raw_fighter_details)
display(stats_processed[stats_processed['event_name']== "UFC Fight Night: Fiziev vs. Torres"])
display(stats_raw)

,red_fighter_name,blue_fighter_name,event_date,red_fighter_nickname,blue_fighter_nickname,red_fighter_result,blue_fighter_result,fight_outcome,method,round,...,blue_fighter_sig_str_distance_landed,blue_fighter_sig_str_distance_attempted,red_fighter_sig_str_clinch_landed,red_fighter_sig_str_clinch_attempted,blue_fighter_sig_str_clinch_landed,blue_fighter_sig_str_clinch_attempted,red_fighter_sig_str_ground_landed,red_fighter_sig_str_ground_attempted,blue_fighter_sig_str_ground_landed,blue_fighter_sig_str_ground_attempted
0,ABDUL RAKHMAN YAKHYAEV,JULIUS WALKER,2026-06-27,The Hunter,Juice Box,W,L,red_win,KO/TKO,1,...,0,1,0,0,0,0,5,7,0,0
1,ABUS MAGOMEDOV,MICHAL OLEKSIEJCZUK,2026-06-27,NaN,Hussar,W,L,red_win,Submission,1,...,5,19,1,1,0,0,0,1,0,0
2,ASU ALMABAYEV,CHARLES JOHNSON,2026-06-27,Zulfikar,InnerG,W,L,red_win,Submission,3,...,18,41,1,1,3,4,9,13,0,0
3,BEKZAT ALMAKHAN,JEAN MATSUMOTO,2026-06-27,The Turan Warrior,NaN,L,W,blue_win,Decision - Unanimous,3,...,70,211,4,4,6,14,0,0,3,4
4,DANIIL DONCHENKO,THEODOR BERGGREN,2026-06-27,NaN,Simba,W,L,red_win,KO/TKO,2,...,20,60,10,13,3,4,0,1,0,0
5,FARMAN HASANOV,ERIC NOLAN,2026-06-27,The Lion,Night Time,W,L,red_win,Decision - Unanimous,3,...,15,51,0,0,0,0,2,4,0,0
6,IKRAM ALISKEROV,BRUNNO FERREIRA,2026-06-27,NaN,The Hulk,W,L,red_win,Decision - Unanimous,3,...,19,55,0,1,0,0,11,13,0,0
7,KAAN OFLI,JAVIER REYES,2026-06-27,Genghis,Blair,W,L,red_win,Submission,1,...,7,35,0,0,0,0,4,5,0,0
8,NAZIM SADYKHOV,MATHEUS CAMILO,2026-06-27,Black Wolf,Jaguar,L,W,blue_win,KO/TKO,1,...,2,6,0,0,0,0,0,0,2,4
9,NURSULTON RUZIBOEV,ANDREY PULYAEV,2026-06-27,Black,NaN,W,L,red_win,Submission,1,...,2,6,0,0,0,0,0,0,0,0
10,RAFAEL FIZIEV,MANUEL TORRES,2026-06-27,Ataman,El Loco,W,L,red_win,KO/TKO,2,...,20,48,3,5,2,4,6,7,0,0
11,SHARA MAGOMEDOV,MICHEL PEREIRA,2026-06-27,Bullet,Demolidor,W,L,red_win,Decision - Unanimous,3,...,19,54,5,6,1,1,3,4,15,27
12,TAHIR ABDULLAYEV,JEFFERSON NASCIMENTO,2026-06-27,Tank,Toddynho,W,L,red_win,KO/TKO,3,...,33,70,4,6,2,2,19,26,0,0

,fighter_name,height,weight,reach,stance,date_of_birth,slpm,str_acc,sapm,str_def,takedowns_avg,takedowns_acc,takedowns_def,sub_avg,str_acc_num,takedowns_acc_num,weight_lbs,reach_inches
0,Aalon Cruz,"6' 0""",145 lbs.,"78""",Switch,1989-09-20,7.58,39%,8.88,58%,0.00,0%,0%,0.0,39.0,0.0,145.0,78.0
1,Aaron Brink,"6' 3""",205 lbs.,NaN,Orthodox,1974-11-12,3.49,42%,5.71,57%,0.00,0%,0%,0.0,42.0,0.0,205.0,NaN
2,Aaron Ely,"5' 8""",135 lbs.,NaN,NaN,1989-03-18,0.82,15%,0.66,69%,2.47,100%,50%,4.9,15.0,100.0,135.0,NaN
3,Aaron Jeffery,"6' 2""",185 lbs.,"74""",Orthodox,1992-11-14,6.21,84%,4.14,39%,0.00,0%,75%,0.0,84.0,0.0,185.0,74.0
4,Aaron Lanfranco,NaN,155 lbs.,NaN,NaN,1986-08-26,0.00,0%,0.00,0%,0.00,0%,0%,0.0,0.0,0.0,155.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3768,Zhang Tiequan,"5' 8""",155 lbs.,"69""",Orthodox,1978-07-25,1.23,36%,2.14,51%,1.95,58%,75%,3.4,36.0,58.0,155.0,69.0
3769,Zhang Weili,"5' 4""",115 lbs.,"63""",Switch,1989-08-13,6.38,45%,4.43,53%,1.26,23%,100%,0.5,45.0,23.0,115.0,63.0
3770,ZHU KANGJIE,"5' 6""",145 lbs.,"70""",Orthodox,1996-01-16,2.93,48%,1.64,66%,0.32,100%,50%,0.0,48.0,100.0,145.0,70.0
3771,Zoila Frausto,"5' 4""",135 lbs.,NaN,Orthodox,NaN,0.77,31%,1.64,53%,0.00,0%,57%,0.0,31.0,0.0,135.0,NaN
3772,Zubaira Tukhugov,"5' 8""",145 lbs.,"68""",Orthodox,1991-01-15,2.54,38%,2.53,63%,2.54,46%,100%,0.0,38.0,46.0,145.0,68.0

,winner_name,loser_name,event_date,method,round,time,time_format,bout_type,event_name,event_location,...,delta_reach,delta_slpm_cs,delta_str_acc_cs,delta_sapm_cs,delta_str_def_cs,delta_td_avg_cs,delta_td_acc_cs,delta_td_def_cs,delta_sub_avg_cs,time_seconds
0,ABDUL RAKHMAN YAKHYAEV,JULIUS WALKER,2026-06-27,KO/TKO,1.0,0:08,3 Rnd (5-5-5),Light Heavyweight Bout,UFC Fight Night: Fiziev vs. Torres,"Baku, Azerbaijan",...,0.00,4.92,15.0,-1.96,17.0,7.04,37.0,0.0,7.4,8
1,ABUS MAGOMEDOV,MICHAL OLEKSIEJCZUK,2026-06-27,Submission,1.0,3:25,3 Rnd (5-5-5),Middleweight Bout,UFC Fight Night: Fiziev vs. Torres,"Baku, Azerbaijan",...,10.16,-2.67,-4.0,-1.11,-4.0,1.51,17.0,48.0,0.6,205
2,ASU ALMABAYEV,CHARLES JOHNSON,2026-06-27,Submission,3.0,3:33,3 Rnd (5-5-5),Flyweight Bout,UFC Fight Night: Fiziev vs. Torres,"Baku, Azerbaijan",...,-12.70,-2.26,2.0,-1.94,-2.0,4.27,29.0,-22.0,1.0,213
3,JEAN MATSUMOTO,BEKZAT ALMAKHAN,2026-06-27,Decision - Unanimous,3.0,5:00,3 Rnd (5-5-5),Bantamweight Bout,UFC Fight Night: Fiziev vs. Torres,"Baku, Azerbaijan",...,0.00,2.77,-1.0,1.06,-3.0,2.85,42.0,-3.0,0.5,300
4,DANIIL DONCHENKO,THEODOR BERGGREN,2026-06-27,KO/TKO,2.0,1:35,3 Rnd (5-5-5),Welterweight Bout,UFC Fight Night: Fiziev vs. Torres,"Baku, Azerbaijan",...,-10.16,4.58,27.0,-7.98,37.0,0.58,33.0,75.0,0.0,95
5,FARMAN HASANOV,ERIC NOLAN,2026-06-27,Decision - Unanimous,3.0,5:00,3 Rnd (5-5-5),Welterweight Bout,UFC Fight Night: Fiziev vs. Torres,"Baku, Azerbaijan",...,0.00,-0.28,17.0,-1.59,26.0,17.00,62.0,-44.0,0.0,300
6,IKRAM ALISKEROV,BRUNNO FERREIRA,2026-06-27,Decision - Unanimous,3.0,5:00,3 Rnd (5-5-5),Middleweight Bout,UFC Fight Night: Fiziev vs. Torres,"Baku, Azerbaijan",...,10.16,2.29,11.0,0.26,-6.0,2.82,46.0,50.0,0.1,300
7,KAAN OFLI,JAVIER REYES,2026-06-27,Submission,1.0,4:16,3 Rnd (5-5-5),Featherweight Bout,UFC Fight Night: Fiziev vs. Torres,"Baku, Azerbaijan",...,-17.78,-3.79,0.0,0.11,15.0,-0.93,-43.0,-50.0,0.7,256
8,MATHEUS CAMILO,NAZIM SADYKHOV,2026-06-27,KO/TKO,1.0,1:31,3 Rnd (5-5-5),Lightweight Bout,UFC Fight Night: Fiziev vs. Torres,"Baku, Azerbaijan",...,0.00,-2.47,-5.0,-2.37,17.0,3.08,8.0,-72.0,0.4,91
9,NURSULTON RUZIBOEV,ANDREY PULYAEV,2026-06-27,Submission,1.0,3:58,3 Rnd (5-5-5),Middleweight Bout,UFC Fight Night: Fiziev vs. Torres,"Baku, Azerbaijan",...,-5.08,-1.22,-9.0,-0.26,-6.0,1.09,64.0,-23.0,0.3,238
10,RAFAEL FIZIEV,MANUEL TORRES,2026-06-27,KO/TKO,2.0,0:15,5 Rnd (5-5-5-5-5),Lightweight Bout,UFC Fight Night: Fiziev vs. Torres,"Baku, Azerbaijan",...,-5.08,-1.86,-4.0,0.57,0.0,-0.32,5.0,14.0,-0.7,15
11,SHARA MAGOMEDOV,MICHEL PEREIRA,2026-06-27,Decision - Unanimous,3.0,5:00,3 Rnd (5-5-5),Middleweight Bout,UFC Fight Night: Fiziev vs. Torres,"Baku, Azerbaijan",...,0.00,1.27,11.0,-0.70,-5.0,-1.11,-52.0,-2.0,-0.6,300
12,TAHIR ABDULLAYEV,JEFFERSON NASCIMENTO,2026-06-27,KO/TKO,3.0,4:28,3 Rnd (5-5-5),Welterweight Bout,UFC Fight Night: Fiziev vs. Torres,"Baku, Azerbaijan",...,7.62,0.14,-6.0,-0.14,-6.0,2.07,33.0,34.0,0.0,268

,red_fighter_name,blue_fighter_name,event_date,red_fighter_nickname,blue_fighter_nickname,red_fighter_result,blue_fighter_result,fight_outcome,method,round,...,blue_fighter_sig_str_distance_landed,blue_fighter_sig_str_distance_attempted,red_fighter_sig_str_clinch_landed,red_fighter_sig_str_clinch_attempted,blue_fighter_sig_str_clinch_landed,blue_fighter_sig_str_clinch_attempted,red_fighter_sig_str_ground_landed,red_fighter_sig_str_ground_attempted,blue_fighter_sig_str_ground_landed,blue_fighter_sig_str_ground_attempted
0,ABDUL RAKHMAN YAKHYAEV,JULIUS WALKER,2026-06-27,The Hunter,Juice Box,W,L,red_win,KO/TKO,1,...,0,1,0,0,0,0,5,7,0,0
1,ABUS MAGOMEDOV,MICHAL OLEKSIEJCZUK,2026-06-27,NaN,Hussar,W,L,red_win,Submission,1,...,5,19,1,1,0,0,0,1,0,0
2,ASU ALMABAYEV,CHARLES JOHNSON,2026-06-27,Zulfikar,InnerG,W,L,red_win,Submission,3,...,18,41,1,1,3,4,9,13,0,0
3,BEKZAT ALMAKHAN,JEAN MATSUMOTO,2026-06-27,The Turan Warrior,NaN,L,W,blue_win,Decision - Unanimous,3,...,70,211,4,4,6,14,0,0,3,4
4,DANIIL DONCHENKO,THEODOR BERGGREN,2026-06-27,NaN,Simba,W,L,red_win,KO/TKO,2,...,20,60,10,13,3,4,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8732,ROYCE GRACIE,JASON DELUCIA,1994-03-11,NaN,NaN,W,L,red_win,Submission,1,...,0,0,0,0,0,0,0,0,0,0
8733,ROYCE GRACIE,MINOKI ICHIHARA,1994-03-11,NaN,NaN,W,L,red_win,Submission,1,...,0,2,0,0,0,0,0,0,3,5
8734,ROYCE GRACIE,PATRICK SMITH,1994-03-11,NaN,NaN,W,L,red_win,KO/TKO,1,...,0,1,1,1,1,1,3,3,0,0
8735,ROYCE GRACIE,REMCO PARDOEL,1994-03-11,NaN,Grizzly,W,L,red_win,Submission,1,...,0,0,0,0,0,0,0,0,0,0
8736,SCOTT MORRIS,SEAN DAUGHERTY,1994-03-11,NaN,NaN,W,L,red_win,Submission,1,...,0,3,1,1,0,1,0,0,0,0

In [39]:
merged_stats_n_scorecards['event_date'].max()

'2026-06-27'

### Fonte de dados
- Local: base_dados/processed_silver/ufc_datalabs  
- Origem: https://github.com/komaksym/UFC-DataLab (projeto de coleta de dados)
- Período coberto: eventos de 1994-03 até 2026-06


#### Resumo 
Está bem relacionado com as duas fonte de cima porém com dados mais atualizados

______________
### UFC fight historical

In [41]:
data_ufc = pd.read_csv(r'C:\Users\edude\OneDrive\Área de Trabalho\Códigos\Faculdade\TCC\LabA\base_dados\processed_bronze\4.ufc_fight_historical\data.csv')

In [46]:
display(data_ufc['date'].max())

'2021-03-20'

### Fonte de dados
- Local: C:\Users\edude\OneDrive\Área de Trabalho\Códigos\Faculdade\TCC\LabA\base_dados\processed_bronze\4.ufc_fight_historical 
- Origem: Keagle - kaggle.com/datasets/rajeevw/ufcdata
- Período coberto: eventos de 1994-03 até 2021-03.


#### Resumo 
Base com dados mais antigos

______________
### Ultimate UFC Dataset

In [63]:
ufc_master = pd.read_csv(r'C:\Users\edude\OneDrive\Área de Trabalho\Códigos\Faculdade\TCC\LabA\base_dados\processed_bronze\2.ultimate_ufc_dataset\ufc_master.csv')

In [64]:
display(ufc_master)

,red_fighter,blue_fighter,red_odds,blue_odds,red_ev,blue_ev,date,location,country,winner,...,finish_round,finish_round_time,total_fight_time_secs,red_dec_odds,blue_dec_odds,red_sub_odds,blue_sub_odds,red_ko_odds,blue_ko_odds,finish_round_time_seconds
0,Israel Adesanya,Joe Pyfer,-130.0,102.0,76.9231,102.0000,2026-03-28,"Seattle, Washington, USA",USA,Blue,...,2.0,4:18,558.0,163.0,900.0,2500.0,400.0,300.0,250.0,258.0
1,Alexa Grasso,Maycee Barber,124.0,-158.0,124.0000,63.2911,2026-03-28,"Seattle, Washington, USA",USA,Red,...,1.0,2:42,162.0,175.0,105.0,1400.0,800.0,2500.0,500.0,162.0
2,Michael Chiesa,Niko Price,-901.0,550.0,11.0988,550.0000,2026-03-28,"Seattle, Washington, USA",USA,Red,...,1.0,1:03,63.0,225.0,900.0,-150.0,1600.0,600.0,1000.0,63.0
3,Julian Erosa,Lerryan Douglas,235.0,-320.0,235.0000,31.2500,2026-03-28,"Seattle, Washington, USA",USA,Blue,...,1.0,3:33,213.0,600.0,500.0,600.0,2000.0,700.0,-150.0,213.0
4,Mansur Abdul-Malik,Yousri Belgaroui,-158.0,124.0,63.2911,124.0000,2026-03-28,"Seattle, Washington, USA",USA,Blue,...,3.0,3:39,819.0,350.0,240.0,800.0,1800.0,240.0,250.0,219.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7172,Duane Ludwig,Darren Elkins,-155.0,135.0,64.5161,135.0000,2010-03-21,"Broomfield, Colorado, USA",USA,Blue,...,1.0,0:44,44.0,NaN,NaN,NaN,NaN,NaN,NaN,44.0
7173,John Howard,Daniel Roberts,-210.0,175.0,47.6190,175.0000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,1.0,2:01,121.0,NaN,NaN,NaN,NaN,NaN,NaN,121.0
7174,Brendan Schaub,Chase Gormley,-260.0,220.0,38.4615,220.0000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,1.0,0:47,47.0,NaN,NaN,NaN,NaN,NaN,NaN,47.0
7175,Mike Pierce,Julio Paulino,-420.0,335.0,23.8095,335.0000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,3.0,5:00,900.0,NaN,NaN,NaN,NaN,NaN,NaN,300.0
7176,Eric Schafer,Jason Brilz,140.0,-160.0,140.0000,62.5000,2010-03-21,"Broomfield, Colorado, USA",USA,Blue,...,3.0,5:00,900.0,NaN,NaN,NaN,NaN,NaN,NaN,300.0

### Fonte de dados
- Local: C:\Users\edude\OneDrive\Área de Trabalho\Códigos\Faculdade\TCC\LabA\base_dados\processed_bronze\ultimate_ufc_dataset
- Origem: Keagle - kaggle.com/datasets/neelagiriaditya/ufc-datasets-1994-2025
- Período coberto: eventos de 2010-03 até 2026-03.

______________
______________
### `Resumo geral das nossas fontes`

A partir da análise inicial das bases disponíveis, principalmente considerando atualização, cobertura temporal, riqueza de variáveis e utilidade para modelagem, definimos como fontes principais do projeto:
- UFC-DataLab
- scrape_ufc_stats
- Ultimate UFC Dataset

Essas bases serão priorizadas porque apresentam dados mais recentes, maior potencial analítico e melhor aderência ao objetivo do TCC, que é estruturar uma base integrada para análise e possível predição de resultados no UFC.
As fontes que, neste primeiro momento, não serão priorizadas na exploração principal são:
- UFC Fight Historical, por conter dados mais antigos e menor alinhamento com as bases mais recentes;
- UFC DATASETS, por possuir cobertura limitada até 2025 e possível sobreposição com outras fontes mais completas.

Apesar disso, essas fontes secundárias não serão descartadas. Elas poderão ser utilizadas de forma complementar caso apresentem variáveis relevantes que não estejam disponíveis nas bases principais. Nesse caso, será realizado um recorte compatível de período, chaves e estrutura dos dados, para incorporar essas features sem comprometer a consistência da base final.

--------
--------
--------

## Construção do dataset do TCC

Vamos iniciar com os seguintes to do:

- Entendimento das bases e identificando novas features com os 3 datasets principais
- Identificar chaves conectando essas fontes
- Criar desenho que conecta os dataset
- Iniciar um EDA

In [ ]:
# Carregar as fontes:

raw_fighter_details = pd.read_csv(r'C:\Users\edude\OneDrive\Área de Trabalho\Códigos\Faculdade\TCC\LabA\base_dados\processed_bronze\3.ufc_datalab\raw_fighter_details.csv')

###Scrape
event_details = pd.read_csv(r'C:\Users\edude\OneDrive\Área de Trabalho\Códigos\Faculdade\TCC\LabA\base_dados\processed_bronze\1.scrape_ufc_stats\event_details.csv')
fight_details = pd.read_csv(r'C:\Users\edude\OneDrive\Área de Trabalho\Códigos\Faculdade\TCC\LabA\base_dados\processed_bronze\1.scrape_ufc_stats\fight_details.csv')
fight_results = pd.read_csv(r'C:\Users\edude\OneDrive\Área de Trabalho\Códigos\Faculdade\TCC\LabA\base_dados\processed_bronze\1.scrape_ufc_stats\fight_results.csv')
fight_stats = pd.read_csv(r'C:\Users\edude\OneDrive\Área de Trabalho\Códigos\Faculdade\TCC\LabA\base_dados\processed_bronze\1.scrape_ufc_stats\fight_stats.csv')


### dim_fighter
dim_fighter = pd.read_csv(r'C:\Users\edude\OneDrive\Área de Trabalho\Códigos\Faculdade\TCC\LabA\base_dados\processed_silver\dim_fighters.csv')

### dim_fight

dim_fight = pd.read_csv(r'C:\Users\edude\OneDrive\Área de Trabalho\Códigos\Faculdade\TCC\LabA\base_dados\processed_silver\dim_fight.csv')

C:\Users\edude\AppData\Local\Temp\ipykernel_13676\975077139.py:15: DtypeWarning: Columns (60,61,108,109,117) have mixed types. Specify dtype option on import or set low_memory=False.
  dim_fight = pd.read_csv(r'C:\Users\edude\OneDrive\Área de Trabalho\Códigos\Faculdade\TCC\LabA\base_dados\processed_silver\dim_fight.csv')

### Estrutura final ficaria desse jeito:

`dim_fights` (C:\Users\edude\OneDrive\Área de Trabalho\Códigos\Faculdade\TCC\LabA\base_dados\processed_silver\dim_fight.csv)

    ↓
base central de lutas e resultados 

-----

`fight_stats` (C:\Users\edude\OneDrive\Área de Trabalho\Códigos\Faculdade\TCC\LabA\base_dados\processed_bronze\1.scrape_ufc_stats\fight_stats.csv)

    ↓
features históricas round-a-round calculadas 

-----

`dim_fighters` (C:\Users\edude\OneDrive\Área de Trabalho\Códigos\Faculdade\TCC\LabA\base_dados\processed_silver\dim_fighters.csv)

    ↓

dados físicos/cadastrais: idade, altura, peso, reach, stance

-----
 
-----

`raw_fighter_details` (C:\Users\edude\OneDrive\Área de Trabalho\Códigos\Faculdade\TCC\LabA\base_dados\processed_bronze\3.ufc_datalab\raw_fighter_details.csv)

    ↓

validação externa, clusterização e sanity check de perfil

### Chaves

In [133]:
dim_fighter_unique = dim_fighter.drop_duplicates(
    subset=["fighter_key"],
    keep="first"
)

In [134]:
fighter_id_map = dim_fighter_unique.set_index("fighter_key")["fighter_id"]

In [135]:
dim_fight["red_fighter_id"] = dim_fight["red_key"].map(fighter_id_map)
dim_fight["blue_fighter_id"] = dim_fight["blue_key"].map(fighter_id_map)

In [136]:
df_master = pd.DataFrame(dim_fight)
df_master.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8737 entries, 0 to 8736
Columns: 150 entries, red_fighter_name to blue_fighter_id
dtypes: float64(58), int64(44), object(48)
memory usage: 10.0+ MB

In [138]:
df_master.shape

(8737, 150)

In [68]:
dados_removidos = ['red_fighter_nickname','blue_fighter_nickname','red_fighter_key','blue_fighter_key', ## Removendo dados string do lutador após termos o identificado pelo id 
'fight_outcome','time', ## Temos esses dados em outras variaveis
'referee','details' ## Informações escritas sobre a luta sem utilidade
]

df_master = df_master.drop(columns=dados_removidos, errors='ignore')

In [69]:
linha = df_master.iloc[500]

linha_dict = linha.to_dict()

linha_dict

{'red_fighter_name': 'ADAM FUGITT',
 'blue_fighter_name': 'ISLAM DULATOV',
 'event_date': '2025-07-19',
 'red_fighter_result': 'L',
 'blue_fighter_result': 'W',
 'method': 'KO/TKO',
 'round': 1,
 'time_format': '3 Rnd (5-5-5)',
 'bout_type': 'Welterweight Bout',
 'bonus': 'perf',
 'event_name': 'UFC 318: Holloway vs. Poirier 3',
 'event_location': 'New Orleans, Louisiana, USA',
 'red_fighter_kd': 0,
 'blue_fighter_kd': 1,
 'red_fighter_sig_str': '14 of 27',
 'blue_fighter_sig_str': '21 of 41',
 'red_fighter_sig_str_pct': 51.0,
 'blue_fighter_sig_str_pct': 51.0,
 'red_fighter_total_str': '16 of 29',
 'blue_fighter_total_str': '23 of 44',
 'red_fighter_td': '0 of 3',
 'blue_fighter_td': '0 of 0',
 'red_fighter_td_pct': 0.0,
 'blue_fighter_td_pct': nan,
 'red_fighter_sub_att': 0,
 'blue_fighter_sub_att': 0,
 'red_fighter_rev': 0,
 'blue_fighter_rev': 0,
 'red_fighter_ctrl': '0:59',
 'blue_fighter_ctrl': '0:02',
 'red_fighter_sig_str_head': '5 of 16',
 'blue_fighter_sig_str_head': '17 of 37',
 'red_fighter_sig_str_body': '2 of 4',
 'blue_fighter_sig_str_body': '3 of 3',
 'red_fighter_sig_str_leg': '7 of 7',
 'blue_fighter_sig_str_leg': '1 of 1',
 'red_fighter_sig_str_distance': '13 of 23',
 'blue_fighter_sig_str_distance': '16 of 35',
 'red_fighter_sig_str_clinch': '1 of 4',
 'blue_fighter_sig_str_clinch': '2 of 3',
 'red_fighter_sig_str_ground': '0 of 0',
 'blue_fighter_sig_str_ground': '3 of 3',
 'red_fighter_sig_str_head_pct': 35.0,
 'blue_fighter_sig_str_head_pct': 80.0,
 'red_fighter_sig_str_body_pct': 14.0,
 'blue_fighter_sig_str_body_pct': 14.0,
 'red_fighter_sig_str_leg_pct': 50.0,
 'blue_fighter_sig_str_leg_pct': 4.0,
 'red_fighter_sig_str_distance_pct': 92.0,
 'blue_fighter_sig_str_distance_pct': 76.0,
 'red_fighter_sig_str_clinch_pct': 7.0,
 'blue_fighter_sig_str_clinch_pct': 9.0,
 'red_fighter_sig_str_ground_pct': 0.0,
 'blue_fighter_sig_str_ground_pct': 14.0,
 'red_fighter_total_pts': nan,
 'blue_fighter_total_pts': nan,
 'time_seconds': 246,
 'red_fighter_sig_str_landed': 14,
 'red_fighter_sig_str_attempted': 27,
 'blue_fighter_sig_str_landed': 21,
 'blue_fighter_sig_str_attempted': 41,
 'red_fighter_sig_str_pct_num': 51.0,
 'blue_fighter_sig_str_pct_num': 51.0,
 'red_fighter_total_str_landed': 16,
 'red_fighter_total_str_attempted': 29,
 'blue_fighter_total_str_landed': 23,
 'blue_fighter_total_str_attempted': 44,
 'red_fighter_td_landed': 0,
 'red_fighter_td_attempted': 3,
 'blue_fighter_td_landed': 0,
 'blue_fighter_td_attempted': 0,
 'red_fighter_td_pct_num': 0.0,
 'blue_fighter_td_pct_num': nan,
 'red_fighter_sig_str_head_landed': 5,
 'red_fighter_sig_str_head_attempted': 16,
 'blue_fighter_sig_str_head_landed': 17,
 'blue_fighter_sig_str_head_attempted': 37,
 'red_fighter_sig_str_body_landed': 2,
 'red_fighter_sig_str_body_attempted': 4,
 'blue_fighter_sig_str_body_landed': 3,
 'blue_fighter_sig_str_body_attempted': 3,
 'red_fighter_sig_str_leg_landed': 7,
 'red_fighter_sig_str_leg_attempted': 7,
 'blue_fighter_sig_str_leg_landed': 1,
 'blue_fighter_sig_str_leg_attempted': 1,
 'red_fighter_sig_str_distance_landed': 13,
 'red_fighter_sig_str_distance_attempted': 23,
 'blue_fighter_sig_str_distance_landed': 16,
 'blue_fighter_sig_str_distance_attempted': 35,
 'red_fighter_sig_str_clinch_landed': 1,
 'red_fighter_sig_str_clinch_attempted': 4,
 'blue_fighter_sig_str_clinch_landed': 2,
 'blue_fighter_sig_str_clinch_attempted': 3,
 'red_fighter_sig_str_ground_landed': 0,
 'red_fighter_sig_str_ground_attempted': 0,
 'blue_fighter_sig_str_ground_landed': 3,
 'blue_fighter_sig_str_ground_attempted': 3,
 'red_fighter_id': 'a01a62132460a98d',
 'blue_fighter_id': 'e803242fb2e41112'}

In [97]:
ufc_dataset[ufc_dataset['name'].str.contains('Adam Fugitt', case=False, na=False)].to_dict()

{'id': {289: 'a01a62132460a98d'},
 'name': {289: 'Adam Fugitt'},
 'nick_name': {289: nan},
 'wins': {289: 10},
 'losses': {289: 5},
 'draws': {289: 0},
 'height': {289: 185.42},
 'weight': {289: 77.11},
 'reach': {289: 195.58},
 'stance': {289: 'Southpaw'},
 'date_of_birth': {289: nan},
 'splm': {289: 4.59},
 'str_acc': {289: 46},
 'sapm': {289: 4.54},
 'str_def': {289: 51},
 'takedowns_avg': {289: 1.83},
 'takedowns_avg_acc': {289: 25},
 'takedowns_def': {289: 50},
 'sub_avg': {289: 0.0},
 'weight_lbs': {289: 77.11},
 'reach_inches': {289: 195.58}}

In [95]:
linha = fighters_dim_final[fighters_dim_final['fighter_id']=='a01a62132460a98d'].iloc[0]
linha.to_dict()

{'fighter_id': 'a01a62132460a98d',
 'fighter_key': 'ADAM FUGITT',
 'fighter_name': 'Adam Fugitt',
 'height': '6\' 1"',
 'weight': '170 lbs.',
 'reach': '77"',
 'stance': 'Southpaw',
 'date_of_birth': '1989-01-12',
 'weight_lbs': 170.0,
 'reach_inches': 77.0,
 'height_cm': 185.42,
 'reach_cm': 195.58,
 'url': 'http://ufcstats.com/fighter-details/a01a62132460a98d',
 'slpm': nan,
 'str_acc': nan,
 'str_acc_num': nan,
 'sapm': nan,
 'str_def': nan,
 'takedowns_avg': nan,
 'takedowns_acc': nan,
 'takedowns_acc_num': nan,
 'takedowns_def': nan,
 'sub_avg': nan,
 'source_match': 'left_only'}

In [42]:
df_master.dtypes.value_counts()

int64      44
object     43
float64    20
Name: count, dtype: int64

In [43]:
colunas_numericas = df_master.select_dtypes(include=['int64', 'float64']).columns.tolist()
colunas_categoricas = df_master.select_dtypes(include='object').columns.tolist()

print("Numéricas:", len(colunas_numericas))
print("Categóricas:", len(colunas_categoricas))

Numéricas: 64
Categóricas: 43

In [45]:
df_master[colunas_categoricas].describe()

,red_fighter_name,blue_fighter_name,event_date,red_fighter_nickname,blue_fighter_nickname,red_fighter_result,blue_fighter_result,fight_outcome,method,time,...,red_fighter_sig_str_clinch,blue_fighter_sig_str_clinch,red_fighter_sig_str_ground,blue_fighter_sig_str_ground,red_fighter_total_pts,blue_fighter_total_pts,red_fighter_key,blue_fighter_key,red_fighter_id,blue_fighter_id
count,8786,8786,8786,6334,6293,8786,8786,8786,8786,8786,...,8786,8786,8786,8786,2071,2071,8786,8786,8776,8781
unique,1986,2516,774,1141,1372,4,4,4,10,336,...,550,528,778,585,177,185,1986,2516,1986,2518
top,JIM MILLER,BRUNO SILVA,2016-11-19,The Predator,The Spartan,W,L,red_win,Decision - Unanimous,5:00,...,0 of 0,0 of 0,0 of 0,0 of 0,- - -,- - -,JIM MILLER,BRUNO SILVA,d1941565abf50b16,18968f97ad34f15c
freq,37,30,25,39,39,5524,5524,5524,3159,4158,...,2103,2148,3144,4044,478,478,37,30,37,22

In [46]:
df_master[colunas_numericas].describe().T

,count,mean,std,min,25%,50%,75%,max
round,8786.0,2.356476,1.015504,1.0,1.0,3.0,3.0,5.0
red_fighter_kd,8786.0,0.245846,0.517092,0.0,0.0,0.0,0.0,5.0
blue_fighter_kd,8786.0,0.186661,0.467239,0.0,0.0,0.0,0.0,6.0
red_fighter_sig_str_pct,8747.0,47.927061,15.952026,0.0,38.0,47.0,57.0,100.0
blue_fighter_sig_str_pct,8728.0,43.836503,16.749702,0.0,33.0,44.0,53.0,100.0
...,...,...,...,...,...,...,...,...
blue_fighter_sig_str_clinch_attempted,8786.0,6.748805,9.170023,0.0,1.0,3.0,9.0,89.0
red_fighter_sig_str_ground_landed,8786.0,5.882427,9.767132,0.0,0.0,2.0,8.0,97.0
red_fighter_sig_str_ground_attempted,8786.0,8.516048,14.214970,0.0,0.0,2.0,11.0,165.0
blue_fighter_sig_str_ground_landed,8786.0,3.739244,7.803343,0.0,0.0,0.0,4.0,136.0
blue_fighter_sig_str_ground_attempted,8786.0,5.451855,10.961744,0.0,0.0,1.0,6.0,163.0

In [50]:
nulos = df_master.isnull().sum().sort_values(ascending=False)

nulos[nulos > 0]

red_fighter_total_pts           6715
blue_fighter_total_pts          6715
bonus                           6240
blue_fighter_td_pct_num         3282
blue_fighter_td_pct             3282
red_fighter_td_pct_num          2828
red_fighter_td_pct              2828
blue_fighter_nickname           2493
red_fighter_nickname            2452
blue_fighter_ctrl                181
red_fighter_ctrl                 181
details                           74
blue_fighter_sig_str_pct          58
blue_fighter_sig_str_pct_num      58
red_fighter_sig_str_pct           39
red_fighter_sig_str_pct_num       39
referee                           27
red_fighter_id                    10
blue_fighter_id                    5
dtype: int64